### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Get JWT
POST localhost:8080/login
Content-Type: application/json

{
  "username": "user",
  "password": "6fd531e4-23f0-4026-8023-598726dc4943"
}

### GET ALL ACCOUNTS
GET http://localhost:8080/account?size=100
Authorization: Basic dXNlcjo4ZGZmZDBhZS03MWE1LTRmYWEtYjJlNS04MjI5MTgwNjM5ZDQ=
