### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### register
POST {{url}}/auth/register
Content-Type: application/json

{
  "name": "Tamer",
  "surname": "Ardal",
  "password": "123456",
  "username": "admin"
}

> {%
    client.global.set("token", response.body.token);

%}

### auth
POST {{url}}/auth/authenticate
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

> {% client.global.set("auth-token", response.body.token);  %}

### GET ALL ACCOUNTS
GET {{url}}/account?size=100
Authorization: Bearer {{token}}
